apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-site
  template:
    metadata:
      labels:
        app: php-site
    spec:
      containers:
        - name: php
          image: php:8.1-fpm-alpine
          volumeMounts:
            - name: code
              mountPath: /var/www/html
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: code
          configMap:
            name: php-site-files
        - name: nginx-config
          configMap:
            name: nginx-conf
